# Generated by Django 5.1.1 on 2024-10-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0002_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(blank=True, choices=[('Not Chosen', 'Not Chosen'), ('Todo', 'Todo'), ('Personal Growth', 'Personal Growth'), ('Money Matter', 'Money Matter'), ('Health', 'Health'), ('Opportunity', 'Opportunity'), ('Homestay', 'Homestay'), ('Stock Market', 'Stock Market'), ('Ecommerce', 'Ecommerce'), ('HouseKeeping', 'HouseKeeping')], max_length=30, null=True),
        ),
    ]
