# Generated by Django 5.1.1 on 2024-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0008_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Chosen', 'Not Chosen'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Pending', 'Pending'), ('Done', 'Done'), ('This Week', 'This Week'), ('This Month', 'This Month'), ('This Year', 'This Year'), ('After Europe', 'After Europe')], max_length=30, null=True),
        ),
    ]
