# Generated by Django 5.1.1 on 2024-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0009_alter_todolist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='day',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
