# Generated by Django 5.1.1 on 2024-10-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0010_todolist_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacelist',
            name='day',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
