# Generated by Django 5.1.1 on 2024-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0014_alter_contactlist_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_item', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, choices=[('Not Chosen', 'Not Chosen'), ('Todo', 'Todo'), ('Personal Growth', 'Personal Growth'), ('Money Matter', 'Money Matter'), ('Health', 'Health'), ('Opportunity', 'Opportunity'), ('Homestay', 'Homestay'), ('Stock Market', 'Stock Market'), ('Ecommerce', 'Ecommerce'), ('HouseKeeping', 'HouseKeeping')], max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('Not Chosen', 'Not Chosen'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Pending', 'Pending'), ('Done', 'Done'), ('This Week', 'This Week'), ('This Month', 'This Month'), ('This Year', 'This Year'), ('After Europe', 'After Europe')], max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('day', models.CharField(blank=True, max_length=30, null=True)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
