# Generated by Django 5.1.1 on 2024-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0016_remove_repairlist_date_added_repairlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainlist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='replacelist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='date_added',
        ),
        migrations.AddField(
            model_name='complainlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complainlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='replacelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replacelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
