# Generated by Django 5.1.1 on 2024-10-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_app', '0017_remove_complainlist_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('homestay_name', models.CharField(max_length=100)),
            ],
        ),
    ]
